### ISSUE TITLE
[v1.443-beta] Newer Waypoint incompatible?

### ISSUE THREAD

**Issue by APGRoboCop** [APGRoboCop/rcbot1#1]
This was tested on DMC Linux Server loading dmc_dmz1_and_dmz3 map - from where I had to create waypoints to prevent the bots going into lava suicide. Also I had made new DMC waypoints for dmc_e1m8 to also prevent bot lava suicide as well, but was done using the older 2006 RCBot v1.441-beta build.

```
Program received signal SIGSEGV, Segmentation fault.
0xf3901f90 in WaypointFindPath(path**, int*, int, int) ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
(gdb) bt
#0  0xf3901f90 in WaypointFindPath(path**, int*, int, int) ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
#1  0xf38d7ebb in BotNavigate_UpdateWaypoint(CBot*) ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
#2  0xf389ab37 in CBot::Think() ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
#3  0xf38ef69d in CBotGlobals::StartFrame() ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
#4  0xf38e49cf in StartFrame() ()
   from /home/desktop/steamcmd/hlds/rcbot/dlls/rcbot_mm.so
#5  0xf3d85285 in api_caller_void_args_void(void const*, void const*) ()
   from /home/desktop/steamcmd/hlds/./dmc/addons/metamod/metamod.so
#6  0xf3d8478f in main_hook_function_void(unsigned int, enum_api_t, unsigned int, void const*) ()
   from /home/desktop/steamcmd/hlds/./dmc/addons/metamod/metamod.so
#7  0xf3d87dae in mm_StartFrame() ()
   from /home/desktop/steamcmd/hlds/./dmc/addons/metamod/metamod.so
#8  0xf77fac28 in SV_Physics () at ../engine/sv_phys.c:1985
#9  0xf77f2b26 in SV_Frame () at ../engine/sv_main.c:9236
#10 0xf77bae92 in _Host_Frame (time=0.00804621354) at ../engine/host.c:1404
#11 0xf77bb252 in Host_Frame (time=0.00804621354, iState=1, 
    stateInfo=0xffffcf5c) at ../engine/host.c:1522
#12 0xf77df8dc in CEngine::Frame (this=0xf78766a0 <g_Engine>)
---Type <return> to continue, or q <return> to quit---
    at ../engine/sys_engine.cpp:245
#13 0xf77dcc43 in RunFrame (this=<optimised out>)
    at ../engine/sys_dll2.cpp:1235
#14 CDedicatedServerAPI::RunFrame (
    this=0xf7871d00 <__g_CDedicatedServerAPI_singleton>)
    at ../engine/sys_dll2.cpp:1226
#15 0x08049c65 in RunServer () at ../dedicated/sys_ded.cpp:766
#16 0x08049472 in main (argc=20, argv=0xffffd194)
    at ../dedicated/sys_ded.cpp:1146

```

**Comment by Manapo74** [comment]
Sven Coop not working, error:
- adding bot
- bot profile HAL brain damaged

**Comment by APGRoboCop** [comment]
Do you have the crash dump or log files referring to any rcbot errors?

**Comment by Manapo74** [comment]
Try to run on your Windows, the game will crashed

**Comment by APGRoboCop** [comment]
Well I'm not sure running it on Windows "Listenserver" mode will work as the same in Dedicated Server. Also I've not had many assistance from Sven Dev Team and the author of those bots is busy with his real life.
